export const MEAL_TYPE = 'MEAL_TYPE'
export const NUMBER_PEOPLE = 'NUMBER_PEOPLE'
export const RESTAURANT = 'RESTAURANT'
export const DISH = 'DISH'
export const ADD_DISH = 'ADD_DISH'
export const NUMBER_SERVINGS = 'NUMBER_SERVINGS'
